import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navigation } from './components/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <header className='bg-slate-900 text-white p-4 text-center'>
          {/* This is Header Layout */}
          <Navigation/>
          </header>
        {children}
        <footer className='w-full h-[50px] bg-green-400 text-center'>This is Footer</footer>
        </body>
    </html>
  );
}
